"""Add nullable marks field to Question model

Revision ID: 60811003aa29
Revises: 726556067b70
Create Date: 2025-04-20 21:41:12.117507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60811003aa29'
down_revision = '726556067b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
