"""Add support for multiple question types and custom marking system

Revision ID: 726556067b70
Revises: 41da9744217a
Create Date: 2025-04-20 19:11:29.745007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726556067b70'
down_revision = '41da9744217a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('matching_pairs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('expected_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('option1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option2',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option3',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('option4',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('correct_option',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wrong_answer_penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('partial_credit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('max_possible_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wrong_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('partial_credits', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answers_data', sa.JSON(), nullable=True))
        batch_op.alter_column('time_taken',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('total_scored')
        batch_op.drop_column('total_questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_scored', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.alter_column('time_taken',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.drop_column('answers_data')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('partial_credits')
        batch_op.drop_column('wrong_answers')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('max_possible_score')
        batch_op.drop_column('total_score')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('partial_credit')
        batch_op.drop_column('wrong_answer_penalty')
        batch_op.drop_column('correct_answer_points')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('option4',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option3',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option2',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('option1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tags')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('image_url')
        batch_op.drop_column('expected_answer')
        batch_op.drop_column('matching_pairs')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('question_type')

    # ### end Alembic commands ###
